# Generated by Django 4.2.4 on 2023-08-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="foraluser",
            name="Bio",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="foraluser",
            name="name",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="foraluser",
            name="email",
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
