# Generated by Django 4.2.4 on 2023-08-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elearning", "0002_foraluser_bio_foraluser_name_alter_foraluser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="foraluser",
            name="avatar",
            field=models.ImageField(default="avatar.svg", null=True, upload_to=""),
        ),
    ]
